[aws]
style = "dimmed red"
symbol = "ğŸ…° "

[cmd_duration]
format = "~[$duration]($style)"

[directory]
truncate_to_repo = false

[git_branch]
style = "bold green"
symbol = "ğŸ…¶ "

[git_status]
conflicted_count.enabled = true
untracked_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
renamed_count.enabled = true
deleted_count.enabled = true
show_sync_count.enabled = true

[nodejs]
style = "bold purple"
symbol = "ğŸ…½ "

[ruby]
symbol = "ğŸ† "
