[aws]
style = "dimmed red"
symbol = "ğŸ…° "

[cmd_duration]
format = "~[$duration]($style)"

[directory]
truncate_to_repo = false

[git_branch]
style = "bold green"
symbol = "ğŸ…¶ "

[git_status]
conflicted = "=$count"
untracked = "?$count"
modified = "!$count"
staged = "+$count"
renamed = "Â»$count"
deleted = "âœ˜$count"

[nodejs]
style = "bold purple"
symbol = "ğŸ…½ "

[ruby]
symbol = "ğŸ† "

[time]
disabled = false
